# Generated by Django 5.1.7 on 2025-03-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("is_avaliable", models.BooleanField(default=True)),
                ("ownerDetails", models.CharField(max_length=100)),
                ("available_from", models.DateTimeField()),
                ("available_to", models.DateTimeField()),
                ("bed_num", models.IntegerField()),
                ("bedroom_num", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("distance_from_campus", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longtitude", models.FloatField()),
                ("geoAdrress", models.CharField(max_length=255)),
            ],
        ),
    ]
