# Generated by Django 5.2 on 2025-04-11 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="avg_rating",
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="bed_num",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="bedroom_num",
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name="Rating",
            fields=[
                ("rating_id", models.AutoField(primary_key=True, serialize=False)),
                ("score", models.IntegerField()),
                (
                    "accommodation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.accommodation",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
        ),
    ]
