# Generated by Django 5.1.7 on 2025-03-30 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_ownerdetails_accommodation_owner_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accommodation",
            name="bed_num",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="bedroom_num",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="latitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="longtitude",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
