# Generated by Django 5.2 on 2025-04-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_accommodation_avg_rating_alter_accommodation_bed_num_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="score",
            field=models.IntegerField(
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
            ),
        ),
    ]
