# Generated by Django 5.1.7 on 2025-03-31 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_rename_ownerdetails_accommodation_owner_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name="accommodation",
            old_name="is_avaliable",
            new_name="is_available",
        ),
        migrations.CreateModel(
            name="CEDARSStaff",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.user",
                    ),
                ),
                ("staff_id", models.CharField(max_length=20, unique=True)),
                ("staff_department", models.CharField(max_length=100)),
            ],
            bases=("app.user",),
        ),
        migrations.CreateModel(
            name="HKUStudent",
            fields=[
                (
                    "user_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="app.user",
                    ),
                ),
                ("HKU_ID", models.CharField(max_length=20, unique=True)),
            ],
            bases=("app.user",),
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "reservation_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("reservation_date", models.DateTimeField()),
                ("check_in_date", models.DateTimeField()),
                ("check_out_date", models.DateTimeField()),
                ("is_cancelled", models.BooleanField(default=False)),
                (
                    "accommodation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.accommodation",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CancelledReservation",
            fields=[
                (
                    "cancellation_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
                (
                    "reservation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.reservation",
                    ),
                ),
            ],
        ),
    ]
