# Generated by Django 5.1.7 on 2025-03-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_user_rename_is_avaliable_accommodation_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cancelledreservation",
            name="cancellation_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
