# Generated by Django 5.1.7 on 2025-04-01 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_cancelledreservation_cancellation_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accommodation",
            old_name="geoAdrress",
            new_name="geoAddress",
        ),
        migrations.RemoveField(
            model_name="accommodation",
            name="longtitude",
        ),
        migrations.AddField(
            model_name="accommodation",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="distance_from_campus",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="accommodation",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=100)),
                ("notification_content", models.TextField()),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
        ),
    ]
