# Generated by Django 5.1.7 on 2025-03-30 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accommodation", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accommodation",
            old_name="ownerDetails",
            new_name="owner_details",
        ),
    ]
